from typing import Protocol

from photoframe_backend.infrastructure.db.models import GenerationJob


class JobRepository(Protocol):
    def create_processing_job(self, *, prompt_id: int, room_id: int, source_bytes: bytes, qr_hash: str) -> GenerationJob: ...

    def get_by_id(self, job_id: int) -> GenerationJob | None: ...

    def get_by_qr_hash(self, qr_hash: str) -> GenerationJob | None: ...

    def get_completed_by_qr_hash(self, qr_hash: str) -> GenerationJob | None: ...

    def save(self, job: GenerationJob) -> GenerationJob: ...
