from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parents[3]
DEFAULT_ENV_FILE = BACKEND_DIR / ".env"

DEFAULT_APP_NAME = "AI Photoframe API"
DEFAULT_APP_ENV = "development"
DEFAULT_PUBLIC_ROOM_SLUG = "ph000000"

DEFAULT_JWT_SECRET = "change-me-in-production"
DEFAULT_JWT_EXPIRE_MINUTES = 60
DEFAULT_ADMIN_USERNAME = "admin"
DEFAULT_ADMIN_PASSWORD = ""

DEFAULT_LOG_FILE_PATH = BACKEND_DIR / "logs" / "backend.log"
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_LOG_MAX_BYTES = 5 * 1024 * 1024
DEFAULT_LOG_BACKUP_COUNT = 3
DEFAULT_LOG_FORMAT = "%(asctime)s %(levelname)s [%(name)s] %(message)s"

DEFAULT_DB_HOST = "localhost"
DEFAULT_DB_PORT = 5432
DEFAULT_DB_NAME = "photoframe"
DEFAULT_DB_USER = "photoframe"
DEFAULT_DB_PASSWORD = "photoframe"

DEFAULT_OPENROUTER_HTTP_REFERER = "https://example.com"
DEFAULT_OPENROUTER_X_TITLE = "AI Photoframe"
DEFAULT_OPENROUTER_PROVIDER_SORT = "throughput"
DEFAULT_OPENROUTER_PREFERRED_MAX_LATENCY = 25
DEFAULT_OPENROUTER_SOURCE_MAX_SIDE = 1280
DEFAULT_OPENROUTER_SOURCE_JPEG_QUALITY = 85
DEFAULT_OPENROUTER_MISSING_IMAGE_RETRIES = 3
DEFAULT_OPENROUTER_RESULT_FORMAT = "jpeg"
DEFAULT_OPENROUTER_JPEG_QUALITY = 85

DEFAULT_STORAGE_MEDIA_DIR = "storage"
DEFAULT_RESULT_RETENTION_DAYS = 7
